smoke_test = false
pre_adv_epochs = 4
early_stop = 500
max_epochs = 1000
network_lr = 1e-3
network_loss = "mse"
use_new_sal = true
rng_seed = 2718

[partial]
epochs_between_regens = 5
partial_batch = 5

[log]
partial_regens_per_log = 10
exp_base_dir = "exps"
log_adv_data = true
exp_name = "low_lr"

[sal]
target_loss = "mse"
xa_grad_reduce = 0.01
deltaall = 20
alpha = 0.5
attack_lr = 1e-3
attack_epochs = 2
theta_lr = 1e-3
theta_epochs = 10
adv_reset_epochs = 5
lr_weight_epsilon = 1e-5

[target]
col_name = "delta_e"

[data]
batch_size = 128
log_loaders = ["piezo"]
use_test_mode = false
test_split_seed = 3141

[cli]
verbosity = "info"
show_progress = true
show_cuda_memory = false

[model]
grad_layers = ["fc16.weight"]
