smoke_test = false
pre_adv_epochs = 10
early_stop = 100
max_epochs = 500
network_lr = 1e-4
network_loss = "smooth_l1"
rng_seed = 2718

[partial]
epochs_between_regens = 10
partial_batch = 20

[log]
partial_regens_per_log = 20
exp_base_dir = "exps"
log_adv_data = true
exp_name = "baseline_attempt4"

[sal]
target_loss = "smooth_l1"
xa_grad_reduce = 0.01
deltaall = 20
alpha = 0.5
attack_lr = 3e-4
attack_epochs = 10
theta_lr = 3e-4
theta_epochs = 3
adv_reset_epochs = 5
lr_weight_epsilon = 1e-12
r_theta_splits = 5

[target]
col_name = "delta_e"

[data]
target = "delta_e"
batch_size = 256
num_sal_samples = 1024
test_split_seed = 3141
dataset_split = 0
test_sets = [
    "Xshift_tsne",
    "Xshift_umap",
    "statY_delta_e",
    "infoY_delta_e",
    "statY_bandgap",
    "infoY_bandgap",
    "Rsplt1",
    "Rsplt2",
    "Rsplt3",
    "Rsplt4",
    "Rsplt5",
    "piezo",
]
no_split_test_sets = ["piezo"]

[cli]
verbosity = "info"
show_progress = true
show_cuda_memory = false

[model]
layer_dims = [2048, 1024, 512]
dropout_prop = 0.5
norm_type = "layer"
grad_layers = ["all"]
ema_start_epoch = 20
ema_decay = 0.99
